package shaimaa.twitter.domain.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.util.UUID;


@Getter
@ToString
public class Tweet {
    private final UUID id;
//    private final UUID userId;
    private final User user;
    private final ZonedDateTime createdAt;
    private String content;

    private Tweet(UUID id, User user, ZonedDateTime createdAt, String content) {
        this.id = id;
        this.user = user;
        this.createdAt = createdAt;
        this.content = content;
    }

    public static Tweet newTweet(UUID userId, String content) {
        return new Tweet(
                UUID.randomUUID(), // id will be generated by the database
                User.of(userId),
                ZonedDateTime.now(),
                content
        );
    }

    public static Tweet of(UUID id) {
        return new Tweet(id, null, ZonedDateTime.now(), null);
    }

    public static Tweet of(UUID id, User user, ZonedDateTime createdAt, String content) {
        return new Tweet(id, user, createdAt, content);
    }
}
